/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ]
}
}
export {};
